const STAC_ENDPOINT = 'https://earth-search.aws.element84.com/v1';
const COLLECTION = 'sentinel-2-l2a';

/**
 * Search Sentinel-2 scenes via Element84 STAC API with automatic pagination.
 * Fetches all matching scenes up to maxTotal (default unlimited).
 */
export async function searchScenes({ bbox, dateStart, dateEnd, maxCloud = 100, maxTotal = Infinity }) {
  const PAGE_SIZE = 250; // Element84 STAC API max per request
  const body = {
    collections: [COLLECTION],
    bbox,
    datetime: `${dateStart}T00:00:00Z/${dateEnd}T23:59:59Z`,
    query: { 'eo:cloud_cover': { lte: maxCloud } },
    limit: Math.min(PAGE_SIZE, maxTotal),
    sortby: [{ field: 'properties.datetime', direction: 'desc' }],
  };

  const all = [];
  let nextBody = body;

  while (true) {
    const res = await fetch(`${STAC_ENDPOINT}/search`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(nextBody),
    });
    if (!res.ok) throw new Error(`STAC API error: ${res.status} ${res.statusText}`);
    const data = await res.json();
    const features = data.features || [];
    all.push(...features);

    // Stop if we've hit the user cap or there are no more pages
    if (all.length >= maxTotal) { all.splice(maxTotal); break; }
    const next = data.links?.find(l => l.rel === 'next');
    if (!next) break;
    // Element84 returns next.body with the token; merge into original body
    nextBody = next.merge === false ? { ...body, ...(next.body || {}) } : { ...body, ...(next.body || {}) };
    if (!next.body) break;
  }

  return all;
}

/**
 * Fetch available collections (for reference).
 */
export async function fetchCollections() {
  const res = await fetch(`${STAC_ENDPOINT}/collections/${COLLECTION}`);
  if (!res.ok) throw new Error('Failed to fetch collection info');
  return res.json();
}

/**
 * Get download commands for selected scenes.
 */
export function buildDownloadCommands(scenes, format = 'aws', bands = ['blue', 'green', 'red']) {
  const lines = [];

  for (const scene of scenes) {
    const id = scene.id;
    const assets = scene.assets || {};

    for (const band of bands) {
      const asset = assets[band];
      if (!asset) continue;
      const href = asset.href;

      const ext = href.endsWith('.jp2') ? 'jp2' : 'tif';
      const filename = `${id}_${band}.${ext}`;
      if (format === 'aws') {
        const s3path = href
          .replace('https://sentinel-cogs.s3.us-west-2.amazonaws.com/', 's3://sentinel-cogs/')
          .replace('https://sentinel-cogs.s3-us-west-2.amazonaws.com/', 's3://sentinel-cogs/');
        lines.push(`aws s3 cp "${s3path}" ./${filename} --no-sign-request`);
      } else if (format === 'curl') {
        lines.push(`curl -L -o "${filename}" "${href}"`);
      } else {
        lines.push(href);
      }
    }
  }

  return lines.join('\n');
}

/**
 * Build a Python script for computing yearly median mosaics with stackstac.
 */
export function buildMosaicScript({ tileIds, yearStart, yearEnd, bands, maxCloud, resolution = 20 }) {
  const tilesRepr = JSON.stringify(tileIds);
  const yearsRepr = JSON.stringify(
    Array.from({ length: yearEnd - yearStart + 1 }, (_, i) => yearStart + i)
  );
  const bandsRepr = JSON.stringify(bands);

  return `#!/usr/bin/env python3
"""
Sentinel-2 L2A Yearly Median Mosaic — MGRS Tiles
Generated by Sentinel-2 Explorer

Dependencies:
    pip install pystac-client stackstac rioxarray rasterio numpy tqdm

Modes
-----
  python script.py              # stream & compute directly (default)
  python script.py --download   # download raw COG tiles to ./raw_scenes/ first,
                                # then compute from local files (faster if re-running)
"""

import re, sys, time, os
from pathlib import Path
import pystac_client
import stackstac
import rioxarray
import numpy as np
from dask.diagnostics import ProgressBar
from tqdm import tqdm

DOWNLOAD_ONLY = "--download" in sys.argv

CATALOG    = "https://earth-search.aws.element84.com/v1"
TILES      = ${tilesRepr}
YEARS      = ${yearsRepr}
BANDS      = ${bandsRepr}
MAX_CLOUD  = ${maxCloud}
RESOLUTION = ${resolution}  # metres — 10 (full res, memory-heavy), 20 (standard), 60 (quick preview)

RAW_DIR = Path("raw_scenes")

# ── helpers ───────────────────────────────────────────────────────────────────
SOUTH_BANDS = set("CDEFGHJKLM")

def mgrs_to_epsg(tile):
    m = re.match(r"(\\d+)([A-Z])", tile)
    if not m:
        return 4326
    zone, band = int(m.group(1)), m.group(2)
    return 32700 + zone if band in SOUTH_BANDS else 32600 + zone

def download_scenes(items, tile, year):
    """Download raw COG bands to raw_scenes/<tile>/<year>/<scene_id>/<band>.tif"""
    import urllib.request
    dest = RAW_DIR / tile / str(year)
    dest.mkdir(parents=True, exist_ok=True)
    print(f"  Downloading {len(items)} scenes × {len(BANDS)} bands to {dest}/")
    for i, item in enumerate(items, 1):
        scene_dir = dest / item.id
        scene_dir.mkdir(exist_ok=True)
        for band in BANDS:
            out = scene_dir / f"{band}.tif"
            if out.exists():
                continue
            href = item.assets.get(band, {}).extra_fields.get("href") or getattr(item.assets.get(band), "href", None)
            if not href:
                continue
            urllib.request.urlretrieve(href, out)
        pct = i / len(items) * 100
        print(f"  [{pct:5.1f}%] scene {i}/{len(items)}: {item.id}", flush=True)
    print(f"  Download complete → {dest}")
    return dest

# ── main ──────────────────────────────────────────────────────────────────────
catalog = pystac_client.Client.open(CATALOG)
total_start = time.time()

for tile in TILES:
    epsg = mgrs_to_epsg(tile)
    for year in YEARS:
        t0 = time.time()
        print(f"\\n{'='*60}")
        print(f"MGRS tile: {tile}  |  year: {year}  |  EPSG:{epsg}  |  {RESOLUTION}m")
        print(f"{'='*60}")

        print("  [1/4] Searching STAC catalog ...")
        items = list(catalog.search(
            collections=["sentinel-2-l2a"],
            query={
                "grid:code": {"eq": f"MGRS-{tile}"},
                "eo:cloud_cover": {"lt": MAX_CLOUD},
            },
            datetime=f"{year}-01-01/{year}-12-31",
        ).items())

        if not items:
            print("  No scenes found, skipping.")
            continue

        print(f"  [1/4] Found {len(items)} scenes (cloud < {MAX_CLOUD}%)")

        if DOWNLOAD_ONLY:
            download_scenes(items, tile, year)
            continue

        print(f"  [2/4] Building lazy {len(items)}-scene stack ...")
        stack = stackstac.stack(
            items,
            assets=BANDS,
            epsg=epsg,
            resolution=RESOLUTION,
            chunksize=512,
        )
        h, w = stack.shape[-2], stack.shape[-1]
        print(f"  [2/4] Stack shape: {len(items)} scenes × {len(BANDS)} bands × {h}px × {w}px")

        print("  [3/4] Computing pixel-wise median (lazy) ...")
        median = stack.median(dim="time")
        median = median.rio.write_crs(f"EPSG:{epsg}")

        out_file = f"S2_median_{tile}_{year}_{RESOLUTION}m.tif"
        print(f"  [4/4] Writing {out_file} (chunk-by-chunk, streaming from S3) ...")
        with ProgressBar():
            median.rio.to_raster(
                out_file,
                driver="GTiff",
                compress="deflate",
                dtype="float64",
                tags={
                    "bands":         ",".join(BANDS),
                    "mgrs_tile":     tile,
                    "year":          str(year),
                    "resolution_m":  str(RESOLUTION),
                    "max_cloud_pct": str(MAX_CLOUD),
                    "scene_count":   str(len(items)),
                },
            )
        elapsed = time.time() - t0
        size_mb = os.path.getsize(out_file) / 1e6
        print(f"  Saved → {out_file}  ({size_mb:.1f} MB, {elapsed:.0f}s)")

total = time.time() - total_start
print(f"\\nAll done in {total:.0f}s.")
`;
}

/**
 * EE scripts appended at end of file — see buildEEGridScript / buildEEMGRSScript below.
 */

/**
 * Build a Python script for computing yearly median mosaics from 50km grid cells (bbox-based).
 * cells = [{ id, bbox: [west, south, east, north] }]
 */
export function buildGridMosaicScript({ cells, yearStart, yearEnd, bands, maxCloud, resolution = 20 }) {
  const cellsRepr = JSON.stringify(cells.map(c => ({ id: c.id, bbox: c.bbox })), null, 2);
  const yearsRepr = JSON.stringify(
    Array.from({ length: yearEnd - yearStart + 1 }, (_, i) => yearStart + i)
  );
  const bandsRepr = JSON.stringify(bands);

  return `#!/usr/bin/env python3
"""
Sentinel-2 L2A Yearly Median Mosaic — 50 km Grid Cells
Generated by Sentinel-2 Explorer

Dependencies:
    pip install pystac-client stackstac rioxarray rasterio numpy tqdm

Modes
-----
  python script.py              # stream & compute directly (default)
  python script.py --download   # download raw COG tiles to ./raw_scenes/ first,
                                # then compute from local files (faster if re-running)
"""

import sys, time, os, urllib.request
from pathlib import Path
import pystac_client
import stackstac
import rioxarray
import numpy as np
from dask.diagnostics import ProgressBar

DOWNLOAD_ONLY = "--download" in sys.argv

CATALOG    = "https://earth-search.aws.element84.com/v1"
CELLS      = ${cellsRepr}
YEARS      = ${yearsRepr}
BANDS      = ${bandsRepr}
MAX_CLOUD  = ${maxCloud}
RESOLUTION = ${resolution}  # metres — 10 (full res, memory-heavy), 20 (standard), 60 (quick preview)

RAW_DIR = Path("raw_scenes")

# ── helpers ───────────────────────────────────────────────────────────────────
def bbox_to_epsg(bbox):
    west, south, east, north = bbox
    lon = (west + east) / 2
    lat = (south + north) / 2
    zone = int((lon + 180) / 6) + 1
    return 32700 + zone if lat < 0 else 32600 + zone

def download_scenes(items, cell_id, year):
    """Download raw COG bands to raw_scenes/<cell_id>/<year>/<scene_id>/<band>.tif"""
    dest = RAW_DIR / cell_id / str(year)
    dest.mkdir(parents=True, exist_ok=True)
    print(f"  Downloading {len(items)} scenes × {len(BANDS)} bands to {dest}/")
    for i, item in enumerate(items, 1):
        scene_dir = dest / item.id
        scene_dir.mkdir(exist_ok=True)
        for band in BANDS:
            out = scene_dir / f"{band}.tif"
            if out.exists():
                continue
            asset = item.assets.get(band)
            if not asset:
                continue
            urllib.request.urlretrieve(asset.href, out)
        pct = i / len(items) * 100
        print(f"  [{pct:5.1f}%] scene {i}/{len(items)}: {item.id}", flush=True)
    print(f"  Download complete → {dest}")

# ── main ──────────────────────────────────────────────────────────────────────
catalog = pystac_client.Client.open(CATALOG)
total_start = time.time()

for cell in CELLS:
    cell_id = cell["id"]
    bbox    = cell["bbox"]
    epsg    = bbox_to_epsg(bbox)

    for year in YEARS:
        t0 = time.time()
        print(f"\\n{'='*60}")
        print(f"Cell: {cell_id}  |  year: {year}  |  EPSG:{epsg}  |  {RESOLUTION}m")
        print(f"bbox: {bbox}")
        print(f"{'='*60}")

        print("  [1/4] Searching STAC catalog ...")
        items = list(catalog.search(
            collections=["sentinel-2-l2a"],
            bbox=bbox,
            query={"eo:cloud_cover": {"lt": MAX_CLOUD}},
            datetime=f"{year}-01-01/{year}-12-31",
        ).items())

        if not items:
            print("  No scenes found, skipping.")
            continue

        print(f"  [1/4] Found {len(items)} scenes (cloud < {MAX_CLOUD}%)")

        if DOWNLOAD_ONLY:
            download_scenes(items, cell_id, year)
            continue

        print(f"  [2/4] Building lazy {len(items)}-scene stack ...")
        stack = stackstac.stack(
            items,
            assets=BANDS,
            epsg=epsg,
            resolution=RESOLUTION,
            bounds_latlon=bbox,
            chunksize=512,
        )
        h, w = stack.shape[-2], stack.shape[-1]
        print(f"  [2/4] Stack shape: {len(items)} scenes × {len(BANDS)} bands × {h}px × {w}px")

        print("  [3/4] Computing pixel-wise median (lazy) ...")
        median = stack.median(dim="time")
        median = median.rio.write_crs(f"EPSG:{epsg}")

        out_file = f"S2_median_{cell_id}_{year}_{RESOLUTION}m.tif"
        print(f"  [4/4] Writing {out_file} (chunk-by-chunk, streaming from S3) ...")
        with ProgressBar():
            median.rio.to_raster(
                out_file,
                driver="GTiff",
                compress="deflate",
                dtype="float64",
                tags={
                    "cell_id":       cell_id,
                    "bbox":          str(bbox),
                    "year":          str(year),
                    "resolution_m":  str(RESOLUTION),
                    "max_cloud_pct": str(MAX_CLOUD),
                    "scene_count":   str(len(items)),
                },
            )
        elapsed = time.time() - t0
        size_mb = os.path.getsize(out_file) / 1e6
        print(f"  Saved → {out_file}  ({size_mb:.1f} MB, {elapsed:.0f}s)")

total = time.time() - total_start
print(f"\\nAll done in {total:.0f}s.")
`;
}

// ── Band name mapping: app keys → Earth Engine band names ──────────────────
const EE_BAND_MAP = {
  blue: 'B2', green: 'B3', red: 'B4', nir: 'B8', nir08: 'B8A',
  rededge1: 'B5', rededge2: 'B6', rededge3: 'B7',
  swir16: 'B11', swir22: 'B12',
};

const EE_CLOUD_MASK_PY = `\n# SCL cloud mask: keep 4=veg 5=soil 6=water 7=unclassified\ndef mask_clouds(image):\n    scl = image.select("SCL")\n    good = scl.eq(4).Or(scl.eq(5)).Or(scl.eq(6)).Or(scl.eq(7))\n    return image.updateMask(good)\n`;

const EE_EXPORT_PY = `\n        if MODE_LOCAL:\n            out_file = f"{label}.tif"\n            print(f"  [3/3] Downloading via High Volume API → {out_file} ...")\n            geemap.download_ee_image(\n                image=composite, filename=out_file,\n                region=geometry, scale=RESOLUTION, crs="EPSG:4326",\n                max_tile_size=4,\n            )\n            elapsed = time.time() - t0\n            print(f"  Saved → {out_file}  ({elapsed:.0f}s)")\n        else:\n            print(f"  [3/3] Submitting Drive export task ...")\n            task = ee.batch.Export.image.toDrive(\n                image=composite, description=label,\n                folder=DRIVE_FOLDER, fileNamePrefix=label,\n                region=geometry, scale=RESOLUTION, crs="EPSG:4326",\n                maxPixels=1e13, fileFormat="GeoTIFF",\n            )\n            task.start()\n            elapsed = time.time() - t0\n            print(f"  Task ID: {task.id}  ({elapsed:.1f}s)")\n            print(f"  Monitor: https://code.earthengine.google.com/tasks")\n`;

function eeDocstring(subject) {
  return `#!/usr/bin/env python3
"""
Sentinel-2 Yearly Median Mosaic — Google Earth Engine (${subject})
Generated by Sentinel-2 Explorer

Dependencies:
    pip install earthengine-api geemap

Authentication (run once):
    earthengine authenticate

Export options:
    python script.py          # export to Google Drive (GEE processes async)
    python script.py --local  # download via High Volume API (faster, no Drive needed)
"""

import os, time, warnings, logging
# Suppress harmless GDAL ExtraSamples / geedim STAC warnings before any imports
os.environ["CPL_LOG"] = "/dev/null"
os.environ["GDAL_PAM_ENABLED"] = "NO"
warnings.filterwarnings("ignore")
logging.getLogger("geedim").setLevel(logging.ERROR)
logging.getLogger("rasterio").setLevel(logging.ERROR)
logging.getLogger("urllib3").setLevel(logging.ERROR)
import ee
import geemap

`;
}

/**
 * GEE script for MGRS tiles.
 */
export function buildEEMGRSScript({ tileIds, yearStart, yearEnd, bands, maxCloud, resolution, project = 'your-gee-project-id', modeLocal = true }) {
  const eeBands = bands.filter(b => EE_BAND_MAP[b]).map(b => EE_BAND_MAP[b]);
  const tilesRepr = JSON.stringify(tileIds);
  const yearsRepr = JSON.stringify(Array.from({ length: yearEnd - yearStart + 1 }, (_, i) => yearStart + i));
  const eeBandsRepr = JSON.stringify(eeBands);

  return eeDocstring('MGRS Tiles') + `PROJECT      = "${project}"
TILES        = ${tilesRepr}
YEARS        = ${yearsRepr}
BANDS        = ${eeBandsRepr}
MAX_CLOUD    = ${maxCloud}
RESOLUTION   = ${resolution}
DRIVE_FOLDER = "sentinel2_mosaics"
MODE_LOCAL   = ${modeLocal ? 'True' : 'False'}  # True = High Volume API (local), False = Google Drive

ee.Initialize(project=PROJECT)
` + EE_CLOUD_MASK_PY + `
import re
total_start = time.time()

for tile in TILES:
    m = re.match(r"(\\d+)", tile)
    zone = int(m.group(1)) if m else 1
    lon_c = (zone - 1) * 6 - 180 + 3
    geometry = ee.Geometry.BBox(lon_c - 3, -84, lon_c + 3, 84)

    for year in YEARS:
        t0 = time.time()
        print(f"\\n{'='*60}")
        print(f"Tile: {tile}  year: {year}  {RESOLUTION}m  cloud<{MAX_CLOUD}%")
        print(f"{'='*60}")
        print("  [1/3] Filtering collection ...")
        col = (ee.ImageCollection("COPERNICUS/S2_SR_HARMONIZED")
            .filterBounds(geometry)
            .filterDate(f"{year}-01-01", f"{year}-12-31")
            .filter(ee.Filter.lt("CLOUDY_PIXEL_PERCENTAGE", MAX_CLOUD))
            .map(mask_clouds)
            .select(BANDS))
        n = col.size().getInfo()
        print(f"  [1/3] {n} scenes after cloud filter")
        print("  [2/3] Computing median on GEE servers ...")
        composite = col.median().clip(geometry)
        label = f"S2_median_{tile}_{year}_{RESOLUTION}m"
` + EE_EXPORT_PY + `
total = time.time() - total_start
if MODE_LOCAL:
    print(f"\\nAll done in {total:.0f}s.")
else:
    print(f"\\nAll {len(TILES) * len(YEARS)} tasks submitted in {total:.0f}s.")
    print("Files appear in Google Drive once GEE finishes processing.")
`;
}

/**
 * GEE script for 50km grid cells.
 */
export function buildEEGridScript({ cells, yearStart, yearEnd, bands, maxCloud, resolution, project = 'your-gee-project-id', modeLocal = true }) {
  const eeBands = bands.filter(b => EE_BAND_MAP[b]).map(b => EE_BAND_MAP[b]);
  const cellsRepr = JSON.stringify(cells.map(c => ({ id: c.id, bbox: c.bbox })), null, 2);
  const yearsRepr = JSON.stringify(Array.from({ length: yearEnd - yearStart + 1 }, (_, i) => yearStart + i));
  const eeBandsRepr = JSON.stringify(eeBands);

  return eeDocstring('50 km Grid Cells') + `PROJECT      = "${project}"
CELLS        = ${cellsRepr}
YEARS        = ${yearsRepr}
BANDS        = ${eeBandsRepr}
MAX_CLOUD    = ${maxCloud}
RESOLUTION   = ${resolution}
DRIVE_FOLDER = "sentinel2_mosaics"
MODE_LOCAL   = ${modeLocal ? 'True' : 'False'}  # True = High Volume API (local), False = Google Drive

ee.Initialize(project=PROJECT)
` + EE_CLOUD_MASK_PY + `
total_start = time.time()

for cell in CELLS:
    cell_id = cell["id"]
    west, south, east, north = cell["bbox"]
    geometry = ee.Geometry.BBox(west, south, east, north)

    for year in YEARS:
        t0 = time.time()
        print(f"\\n{'='*60}")
        print(f"Cell: {cell_id}  year: {year}  {RESOLUTION}m  cloud<{MAX_CLOUD}%")
        print(f"bbox: [{west}, {south}, {east}, {north}]")
        print(f"{'='*60}")
        print("  [1/3] Filtering collection ...")
        col = (ee.ImageCollection("COPERNICUS/S2_SR_HARMONIZED")
            .filterBounds(geometry)
            .filterDate(f"{year}-01-01", f"{year}-12-31")
            .filter(ee.Filter.lt("CLOUDY_PIXEL_PERCENTAGE", MAX_CLOUD))
            .map(mask_clouds)
            .select(BANDS))
        n = col.size().getInfo()
        print(f"  [1/3] {n} scenes after cloud filter")
        print("  [2/3] Computing median on GEE servers ...")
        composite = col.median().clip(geometry)
        label = f"S2_median_{cell_id}_{year}_{RESOLUTION}m"
` + EE_EXPORT_PY + `
total = time.time() - total_start
if MODE_LOCAL:
    print(f"\\nAll done in {total:.0f}s.")
else:
    print(f"\\nAll {len(CELLS) * len(YEARS)} tasks submitted in {total:.0f}s.")
    print("Files appear in Google Drive once GEE finishes processing.")
`;
}
